config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show]
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do 
    member do 
      get :toggle_status
    end
  end
  
  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies, reject_if: ->(attributes){ attributes['name'].blank? }, allow_destroy: true
  
  include Placeholder
  validates :title, presence: true
  validates :main_image, presence: true
  validates :thumb_image, presence: true

  def self.angular 
    where(subtitle: 'Angular')
  end

  scope :ruby_on_rails, -> { where(subtitle: 'Ruby on Rails')}

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: %i[ show edit update destroy ]
  layout "portfolio"

  def index
    @portfolios = Portfolio.all
  end 

  def angular
    @angular_portfolios = Portfolio.angular
  end

  def new
    @portfolio = Portfolio.new
    3.times { @portfolio.technologies.build }
  end

  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to portfolios_path, notice: "Portfolio was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @portfolio = Portfolio.find(params[:id])
  end

  def update
    @portfolio = Portfolio.find(params[:id])
    
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: "Portfolio was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def destroy
    @portfolio.destroy

    respond_to do |format|
      format.html { redirect_to portfolios_path, notice: "Portfolio was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def portfolio_params
      params.require(:portfolio).permit(:title, 
                                        :subtitle, 
                                        :body, 
                                        technologies_attributes: [:name]
                                      )
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_area :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <ul>
    <%= form.fields_for :technologies do |technology_form| %>
      <li>
        <%= technology_form.label :name %>
        <%= technology_form.text_field :name %>
      </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/_portfolio.html.erb
  <p><%= link_to portfolio.title, portfolio_show_path(portfolio) %><p>
  <p><%= portfolio.subtitle %><p>
  <p><%= portfolio.body %><p>
  <%= image_tag portfolio.thumb_image if !portfolio.thumb_image.nil? %>
  <%= link_to 'Edit', edit_portfolio_path(portfolio) %>
  <td><%= link_to 'Delete Portfolio', portfolio_path(portfolio), method: :delete, data: { confirm: 'Are you sure?' } %></td>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items<h1>

<%= link_to 'Create New Item', new_portfolio_path %>

<% @angular_portfolios.each do |portfolio| %>
  <p><%= link_to portfolio.title, portfolio_show_path(portfolio) %><p>
  <p><%= portfolio.subtitle %><p>
  <p><%= portfolio.body %><p>
  <%= image_tag portfolio.thumb_image if !portfolio.thumb_image.nil? %>
  <%= link_to 'Edit', edit_portfolio_path(portfolio) %>
  <td><%= link_to 'Delete Portfolio', portfolio_path(portfolio), method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Edit this Portfolio Item</h1>

<%= render 'form', portfolio: @portfolio %>

app/views/portfolios/index.html.erb
<h1>Portfolio Items<h1>

<%= link_to 'Create New Item', new_portfolio_path %>

<%= render @portfolios %>

app/views/portfolios/new.html.erb
<h1>Create a new Portfolio Item</h1>

<%= render 'form', portfolio: @portfolio %>

app/views/portfolios/show.html.erb
<%= image_tag @portfolio.main_image %>
<h1><%= @portfolio.title %></h1>

<em><%= @portfolio.subtitle %></em>

<p><%= @portfolio.body %></p>

<h2>Technologies Used</h2>

<% @portfolio.technologies.each do |t| %>
  <p><%= t.name %></p>
<% end %>